// labels.ts

export const COCO_LABELS = [
    'person',
    'bicycle',
    'car',
    'motorcycle',
    'airplane',
    'bus',
    'train',
    'truck',
    'boat',
    'traffic light',
    'fire hydrant',
    'stop sign',
    'parking meter',
    'bench',
    'bird',
    'cat',
    'dog',
    'horse',
    'sheep',
    'cow',
    'elephant',
    'bear',
    'zebra',
    'giraffe',
    'backpack',
    'umbrella',
    'handbag',
    'tie',
    'suitcase',
    'frisbee',
    'skis',
    'snowboard',
    'sports ball',
    'kite',
    'baseball bat',
    'baseball glove',
    'skateboard',
    'surfboard',
    'tennis racket',
    'bottle',
    'wine glass',
    'cup',
    'fork',
    'knife',
    'spoon',
    'bowl',
    'banana',
    'apple',
    'sandwich',
    'orange',
    'broccoli',
    'carrot',
    'hot dog',
    'pizza',
    'donut',
    'cake',
    'chair',
    'couch',
    'potted plant',
    'bed',
    'dining table',
    'toilet',
    'tv',
    'laptop',
    'mouse',
    'remote',
    'keyboard',
    'cell phone',
    'microwave',
    'oven',
    'toaster',
    'sink',
    'refrigerator',
    'book',
    'clock',
    'vase',
    'scissors',
    'teddy bear',
    'hair drier',
    'toothbrush',
  ];
  
  // Add translations for each label
  export const LABEL_TRANSLATIONS: { [key: string]: { [lang: string]: string } } = {
    person: { es: 'persona' },
    bicycle: { es: 'bicicleta' },
    car: { es: 'coche' },
    motorcycle: { es: 'motocicleta' },
    airplane: { es: 'avión' },
    bus: { es: 'autobús' },
    train: { es: 'tren' },
    truck: { es: 'camión' },
    boat: { es: 'barco' },
    'traffic light': { es: 'semáforo' },
    'fire hydrant': { es: 'boca de incendios' },
    'stop sign': { es: 'señal de stop' },
    'parking meter': { es: 'parquímetro' },
    bench: { es: 'banco' },
    bird: { es: 'pájaro' },
    cat: { es: 'gato' },
    dog: { es: 'perro' },
    horse: { es: 'caballo' },
    sheep: { es: 'oveja' },
    cow: { es: 'vaca' },
    elephant: { es: 'elefante' },
    bear: { es: 'oso' },
    zebra: { es: 'cebra' },
    giraffe: { es: 'jirafa' },
    backpack: { es: 'mochila' },
    umbrella: { es: 'paraguas' },
    handbag: { es: 'bolso' },
    tie: { es: 'corbata' },
    suitcase: { es: 'maleta' },
    frisbee: { es: 'frisbee' },
    skis: { es: 'esquís' },
    snowboard: { es: 'tabla de snowboard' },
    'sports ball': { es: 'pelota deportiva' },
    kite: { es: 'cometa' },
    'baseball bat': { es: 'bate de béisbol' },
    'baseball glove': { es: 'guante de béisbol' },
    skateboard: { es: 'monopatín' },
    surfboard: { es: 'tabla de surf' },
    'tennis racket': { es: 'raqueta de tenis' },
    bottle: { es: 'botella' },
    'wine glass': { es: 'copa de vino' },
    cup: { es: 'taza' },
    fork: { es: 'tenedor' },
    knife: { es: 'cuchillo' },
    spoon: { es: 'cuchara' },
    bowl: { es: 'cuenco' },
    banana: { es: 'plátano' },
    apple: { es: 'manzana' },
    sandwich: { es: 'sándwich' },
    orange: { es: 'naranja' },
    broccoli: { es: 'brócoli' },
    carrot: { es: 'zanahoria' },
    'hot dog': { es: 'perrito caliente' },
    pizza: { es: 'pizza' },
    donut: { es: 'donut' },
    cake: { es: 'pastel' },
    chair: { es: 'silla' },
    couch: { es: 'sofá' },
    'potted plant': { es: 'planta en maceta' },
    bed: { es: 'cama' },
    'dining table': { es: 'mesa de comedor' },
    toilet: { es: 'inodoro' },
    tv: { es: 'televisión' },
    laptop: { es: 'portátil' },
    mouse: { es: 'ratón' },
    remote: { es: 'mando a distancia' },
    keyboard: { es: 'teclado' },
    'cell phone': { es: 'teléfono móvil' },
    microwave: { es: 'microondas' },
    oven: { es: 'horno' },
    toaster: { es: 'tostadora' },
    sink: { es: 'fregadero' },
    refrigerator: { es: 'refrigerador' },
    book: { es: 'libro' },
    clock: { es: 'reloj' },
    vase: { es: 'jarrón' },
    scissors: { es: 'tijeras' },
    'teddy bear': { es: 'oso de peluche' },
    'hair drier': { es: 'secador de pelo' },
    toothbrush: { es: 'cepillo de dientes' },
  };
  
  // Helper function to get translation
  export const getTranslation = (label: string, lang: string = 'es'): string => {
    return LABEL_TRANSLATIONS[label]?.[lang] || label;
  };